name: iOS FS Extractor
on:
  push:
jobs:
  Extract:
    name: iOS FS Extractor
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with: 
          python-version: 3.12
      - name: Test
        run: |
             pip imstall request pyhpke
             #aea
