name: iOS FS Extractor
on:
  push:
jobs:
  Extract:
    name: iOS FS Extractor
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download IPSW
        run: curl "https://updates.cdn-apple.com/2024SummerSeed/fullrestores/052-34764/D5D3D10C-E557-4A46-8EBD-290411A228AA/iPhone16,2_18.0_22A5282m_Restore.ipsw" -o IPSW.ipsw
      - name: Extract IPSW
        run: unzip *.ipsw -d ExtractedIPSW
      - name: Mount DMG
        run: |
             python Decrypt_RootFS.py ExtractedIPSW/$(/usr/libexec/PlistBuddy -c "print BuildIdentities:0:Manifest:OS:Info:Path" ExtractedIPSW/BuildManifest.plist)
             hdiutil attach -mountpoint FS RootFS.dmg
        run: rm *.ipsw && rm -rf ExtractedIPSW
      - name: Make Zip
        run: |
             mkdir Stuff
             cp -r FS/System/Library/PrivateFrameworks/MobileIcons.framework Stuff
             cp -r FS/System/Library/CoreServices Stuff
             zip -r9 "RootFS.zip" Stuff
      - name: Upload 
        uses: actions/upload-artifact@v3
        with:
          name: File.zip
          path: "*.zip"
