name: iOS FS Extractor
on:
  push:
jobs:
  Extract:
    name: iOS FS Extractor
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with: 
          python-version: 3.12
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            requests
            pyhpke
      - name: Download IPSW
        run: curl "${{inputs.IPSW}}" -o IPSW.ipsw
      - name: Extract IPSW
        run: unzip *.ipsw -d ExtractedIPSW
      - name: Mount DMG
        run: |
             python get_key.py ExtractedIPSW/$(/usr/libexec/PlistBuddy -c "print BuildIdentities:0:Manifest:OS:Info:Path" ExtractedIPSW/BuildManifest.plist)
             hdiutil attach -mountpoint FS test.dmg
      - name: Clean Up
        run: rm *.ipsw && rm -rf ExtractedIPSW
      - name: Make Zip
        run: |
             ls FS
             echo end here
             ls FS/System/Library
             FilePath="FS${{inputs.Path}}"
             FileName=$(basename "$FilePath")
             #zip -r9 "$FileName.zip" "$FilePath"
             mkdir Stuff
             cp -r FS/System/Library/CoreServices/SpringBoard.app Stuff
             cp -r FS/System/Library/ControlCenter Stuff
             zip -r9 "$FileName.zip" Stuff
      - name: Upload 
        uses: actions/upload-artifact@v3
        with:
          name: File.zip
          path: "*.zip"
